name: Dotnet SpecFlow test

on: [push]

jobs:
  build-and-test:

    runs-on: ubuntu-latest
    services:
      activemq:
        image: apache/activemq-classic:6.1.0
        ports:
          - 28161:8161
          - 21616:61616
      challenge-server:
        image: wiremock/wiremock:3.7.0
        ports:
          - 8222:8080
      recording-server:
        image: wiremock/wiremock:3.7.0
        ports:
          - 41375:8080
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'true'

      # ~~~~~~~~~~~~~ .Net setup ~~~~~~~~~~~~~
      - name: Set up dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0'
          cache: true
      - name: Install dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build

      # ~~~~~~~~~~~~~ Test ~~~~~~~~~~~~~
      - name: Test with the dotnet CLI
        run: dotnet test
