name: Publish to PyPi

on:
  push:
    tags:
      - v*

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # ~~~~~~~~~~~~~ .Net setup ~~~~~~~~~~~~~
      - name: Set up dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0'
          cache: true
      - name: Display dotnet version
        run: dotnet --version
      - name: Install dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --configuration Release


      # ~~~~~~~~~~~~~ Push to NuGet ~~~~~~~~~~~~~
      - name: Pack
        run: dotnet pack --configuration Release src/Client
      - name: Publish the package to NuGet
        run: dotnet nuget push src/Client/bin/Release/*.nupkg --api-key "$NUGET_TOKEN" --source https://api.nuget.org/v3/index.json
        env:
          NUGET_AUTH_TOKEN: ${{secrets.NUGET_TOKEN}}
