name: Create Github release

on:
  push:
    tags:
      - v*

permissions:
  contents: write

jobs:
  build_and_release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # ~~~~~~~~~~~~~ .Net setup ~~~~~~~~~~~~~
      - name: Set up dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0'
      - name: Display dotnet version
        run: dotnet --version
      - name: Install dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --configuration Release

      # ~~~~~~~~~~~~~ Asset upload ~~~~~~~~~~~~~
      - name: Pack
        run: dotnet pack --configuration Release src/Client
      - name: Standardise dist name
        run: cp src/Client/bin/Release/*.nupkg src/Client/bin/Release/TDL.Client.nupkg

      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: src/Client/bin/Release/TDL.Client.nupkg
